# Generated by Django 4.2 on 2026-02-12 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('density', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Плотность (г/см³)')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('order_name', models.CharField(max_length=200, verbose_name='Наименование заказа')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Коэффициент массы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование детали')),
            ],
            options={
                'verbose_name': 'Наименование детали',
                'verbose_name_plural': 'Наименования деталей',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('sheet', 'Лист'), ('round', 'Кругляк'), ('hexagon', 'Шестигранник')], max_length=20, verbose_name='Тип сортамента')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина (мм)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина (мм)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Высота (мм)')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Диаметр (мм)')),
                ('round_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина (мм)')),
                ('key_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Размер под ключ (мм)')),
                ('hex_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина (мм)')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество на складе')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Сортамент на складе',
                'verbose_name_plural': 'Сортамент на складе',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(verbose_name='Порядковый номер')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество деталей')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Длина (мм)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина (мм)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Высота (мм)')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Диаметр (мм)')),
                ('key_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Размер под ключ (мм)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.material', verbose_name='Марка материала')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.order', verbose_name='Заказ')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.partname', verbose_name='Наименование детали')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.stockitem', verbose_name='Сортамент со склада')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
                'ordering': ['sequence_number'],
            },
        ),
    ]
