# Generated by Django 6.0.1 on 2026-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер чертежа'),
        ),
    ]
