# Generated by Django 6.0.1 on 2026-02-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_order_drawing_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='hex_length',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='round_length',
        ),
    ]
