# Generated by Django 6.0.1 on 2026-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_stockitem_height_remove_stockitem_hex_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sequence_number',
            field=models.CharField(max_length=20, verbose_name='Порядковый номер'),
        ),
    ]
