# Generated by Django 6.0.1 on 2026-02-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_orderitem_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Особая запись'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculator.material', verbose_name='Марка материала'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calculator.stockitem', verbose_name='Сортамент со склада'),
        ),
    ]
