# Generated by Django 4.2.15 on 2026-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_orderitem_is_special_alter_orderitem_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='use_iz_prefix',
            field=models.BooleanField(default=False, verbose_name='Добавлять "из" перед размером'),
        ),
    ]
