# Generated by Django 4.2.15 on 2026-05-20 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_orderitem_use_iz_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Коэффициент массы'),
        ),
    ]
