# Generated by Django 4.2.15 on 2026-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_order_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='designation',
            field=models.CharField(blank=True, help_text='Необязательное обозначение детали (до 20 символов)', max_length=20, null=True, verbose_name='Обозначение'),
        ),
    ]
