# Generated by Django 4.2.15 on 2026-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_orderitem_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='designation',
            field=models.CharField(blank=True, help_text='Необязательное обозначение детали (до 40 символов)', max_length=40, null=True, verbose_name='Обозначение'),
        ),
    ]
