# Generated by Django 4.2.15 on 2026-06-18 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_orderitem_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=1, help_text='Количество таких заказов', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Заказ количество'),
        ),
    ]
