# Generated by Django 4.2.15 on 2026-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_order_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='designation',
            field=models.CharField(blank=True, help_text='Необязательное обозначение детали (до 100 символов)', max_length=100, null=True, verbose_name='Обозначение'),
        ),
    ]
