# Generated by Django 4.2.15 on 2026-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_orderitem_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='outer_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Внешний диаметр (мм)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Толщина стенки (мм)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='section_type',
            field=models.CharField(choices=[('sheet', 'Лист'), ('round', 'Кругляк'), ('hexagon', 'Шестигранник'), ('tube', 'Труба')], max_length=20, verbose_name='Тип сортамента'),
        ),
    ]
